
CREATE TABLE MANGA_COMIC (
    COMIC_ID INT,
    COMIC_NAME VARCHAR(20),
    TYPE VARCHAR(10),
    AUTHOR VARCHAR(20),
    RELEASED DATE,
    EPISODES INT,
    RATING INT,
    COMIC_STATUS VARCHAR(10),
    CONSTRAINT COMIC_RATING CHECK (RATING <= 10.00),
    CONSTRAINT COMIC_TYPE CHECK ((TYPE = 'TV-SERIES') OR (TYPE = 'MOVIE')
        OR (TYPE = 'OVA')),
    CONSTRAINT MANGA_COMIC_PK PRIMARY KEY (COMIC_NAME)
);

CREATE TABLE AUTHOR (
    AUTHOR_ID INT,
    AUTHOR_NAME VARCHAR(20),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    COMIC_NAME VARCHAR(20),
    RATING INT,
    CONSTRAINT AUTHOR_RATING CHECK (RATING <= 10.00),
    CONSTRAINT AUTHOR_GENDER CHECK ((GENDER = 'MALE') OR (GENDER = 'FEMALE')),
    CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE CHARACTERS (
    CHARACTER_ID INT,
    CHAR_NAME VARCHAR(20),
    COMIC_NAME VARCHAR(20),
    GENDER VARCHAR(10),
    RATING INT,
    CONSTRAINT CHAR_RATING CHECK (RATING <= 10.00),
    CONSTRAINT CHAR_GENDER CHECK ((GENDER = 'MALE') OR (GENDER = 'FEMALE')),
    CONSTRAINT CHARACTER_PK PRIMARY KEY (CHARACTER_ID)
);


CREATE TABLE THEME_SONG (
    SONG_ID INT,
    NAME VARCHAR(20),
    ARTIST VARCHAR(20),
    COMIC_NAME VARCHAR(20),
    DURATION INT,
    RATING INT,
    CONSTRAINT SONG_RATING CHECK (RATING <= 10.00),
    CONSTRAINT SONG_LENGTH CHECK (DURATION <= 2.00),
    CONSTRAINT SONG_PK PRIMARY KEY (SONG_ID)
);

CREATE TABLE SHOW_DETAILS (
    COMIC_ID INT,
    COMIC_NAME VARCHAR(20),
    CHANNEL_NAME VARCHAR(20),
    DETAILS VARCHAR(30),
    CONSTRAINT SHOW_DETAILS_PK PRIMARY KEY (COMIC_ID)
);

CREATE TABLE PUBLISHER (
    PUBLISHER_ID INT,
    PUBLISHER_NAME VARCHAR(20),
    CHANNEL_NAME VARCHAR(20),
    COMIC_NAME VARCHAR(20),
    LANGUAGES VARCHAR(20),
    LINK VARCHAR(20),
    RATING INT,
    CONSTRAINT P_RATING CHECK (RATING <= 10.00),
    CONSTRAINT PUBLISHER_PK PRIMARY KEY (PUBLISHER_ID)
);

CREATE TABLE VIDEOS (
    VIDEO_ID INT,
    HOSTNAME VARCHAR(20),
    COMIC_NAME VARCHAR(20),
    LINK VARCHAR(20),
    RATING INT,
    CONSTRAINT VIDEO_RATING CHECK (RATING <= 10.00),
	CONSTRAINT VIDEOS_PK PRIMARY KEY (VIDEO_ID)
);

CREATE TABLE USERS (
    USER_ID INT,
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(20),
    COMIC_NAME VARCHAR(20),
    STATUS VARCHAR(20),
    RATING INT,
    CONSTRAINT USER_RATING CHECK (RATING <= 10.00),
    CONSTRAINT CHECK_STATUS CHECK ((STATUS = 'WILL-WATCH')
        OR (STATUS = 'WATCHED')
        OR (STATUS = 'WATCHING')),
    CONSTRAINT USER_ID PRIMARY KEY (USER_ID)
);

SELECT * FROM MANGA_COMIC;
SELECT * FROM CHARACTERS;
SELECT * FROM AUTHOR;
SELECT * FROM PUBLISHER;
SELECT * FROM SHOW_DETAILS;
SELECT * FROM THEME_SONG;
SELECT * FROM USERS;
SELECT * FROM VIDEOS;

DROP TABLE CHARACTERS;
DROP TABLE AUTHOR;
DROP TABLE PUBLISHER;
DROP TABLE SHOW_DETAILS;
DROP TABLE THEME_SONG;
DROP TABLE USERS;
DROP TABLE VIDEOS;
DROP TABLE MANGA_COMIC;

ALTER TABLE CHARACTERS
ADD CONSTRAINT MANGA_COMIC_FK
FOREIGN KEY(COMIC_NAME)
REFERENCES MANGA_COMIC(COMIC_NAME);

ALTER TABLE AUTHOR
ADD CONSTRAINT MANGA_COMIC_FK1
FOREIGN KEY(COMIC_NAME)
REFERENCES MANGA_COMIC(COMIC_NAME);

ALTER TABLE PUBLISHER
ADD CONSTRAINT MANGA_COMIC_FK2
FOREIGN KEY(COMIC_NAME)
REFERENCES MANGA_COMIC(COMIC_NAME);

ALTER TABLE SHOW_DETAILS
ADD CONSTRAINT MANGA_COMIC_FK3
FOREIGN KEY(COMIC_NAME)
REFERENCES MANGA_COMIC(COMIC_NAME);

ALTER TABLE THEME_SONG
ADD CONSTRAINT MANGA_COMIC_FK4
FOREIGN KEY(COMIC_NAME)
REFERENCES MANGA_COMIC(COMIC_NAME);

ALTER TABLE USERS
ADD CONSTRAINT MANGA_COMIC_FK5
FOREIGN KEY(COMIC_NAME)
REFERENCES MANGA_COMIC(COMIC_NAME);

ALTER TABLE VIDEOS
ADD CONSTRAINT MANGA_COMIC_FK6
FOREIGN KEY(COMIC_NAME)
REFERENCES MANGA_COMIC(COMIC_NAME);

INSERT INTO MANGA_COMIC VALUES(1, 'NARUTO-ORIGINAL', 'TV-SERIES', 'Masashi Kishimoto', '2002-10-04', 220, 9,  'COMPLETED');
INSERT INTO MANGA_COMIC VALUES(2, 'NARUTO-SHIPPUDEN', 'TV-SERIES', 'Masashi Kishimoto', '2007-02-16', 500, 10, 'COMPLETED');
INSERT INTO MANGA_COMIC VALUES(3, 'BORUTO: THE MOVIE OF NARUTO', 'MOVIE', 'UKYO KODACHI', '2015-08-08', 4, 9, 'COMPLETED');
INSERT INTO MANGA_COMIC VALUES(4, 'BORUTO: NEXT GENERATIONS', 'TV-SERIES', 'UKYO KODACHI', '2017-04-06', 83, 9, 'ON-GOING');
INSERT INTO MANGA_COMIC VALUES(5, 'The Day Naruto Became Hokage', 'OVA', 'Masashi Kishimoto', '2016-05-05', 1, 9, 'COMPLETED');
INSERT INTO MANGA_COMIC VALUES(6, 'BOKU NO HERO ACADEMIA', 'TV-SERIES', 'Kohei Horikoshi', '2016-05-05', 75, 10, 'ON-GOING');
INSERT INTO MANGA_COMIC VALUES(7, 'KIMI NO-NA-WA', 'MOVIE', 'MAKATO SHINKAI', '2016-05-04', 1, 10, 'COMPLETED');

INSERT INTO CHARACTERS VALUES( 1, 'NARUTO', 'NARUTO-ORIGINAL', 'MALE', 9.63);
INSERT INTO CHARACTERS VALUES( 2, 'KAKASHI', 'NARUTO-ORIGINAL', 'MALE', 8.97);
INSERT INTO CHARACTERS VALUES( 3, 'SAKURA', 'NARUTO-ORIGINAL', 'FEMALE', 8.77);
INSERT INTO CHARACTERS VALUES( 4, 'YAMATO', 'NARUTO-ORIGINAL', 'MALE', 8.33);
INSERT INTO CHARACTERS VALUES( 5, 'SASUKE', 'NARUTO-ORIGINAL', 'MALE', 8.13);

INSERT INTO AUTHOR VALUES(1, 'Kohei Horikoshi', '1987-07-09', 'MALE', 'BOKU NO HERO ACADEMIA', 9.14);
INSERT INTO AUTHOR VALUES(2, 'Masashi Kishimoto', '1974-11-08', 'MALE', 'NARUTO-ORIGINAL', 7.65);
INSERT INTO AUTHOR VALUES(3, 'MAKATO SHINKAI', '1983-02-19', 'MALE', 'KIMI NO-NA-WA', 10);
INSERT INTO AUTHOR VALUES(4, 'UKYO KODACHI', '1979-04-01', 'MALE', 'BORUTO: NEXT GENERATIONS', 7.61);
INSERT INTO AUTHOR VALUES(5, 'Masashi Kishimoto', '1974-11-08', 'MALE', 'NARUTO-SHIPPUDEN', 7.63);

INSERT INTO THEME_SONG VALUES(1, 'GO ON', 'THE TEANGENT','KIMI NO-NA-WA', 1.57, 9.6);
INSERT INTO THEME_SONG VALUES(2, 'No Boy,No Cry', 'Stance Punks','NARUTO-ORIGINAL', 1.24, 7.65);
INSERT INTO THEME_SONG VALUES(3, 'DIVER', 'ELENA','NARUTO-SHIPPUDEN', 1.59, 8.21);
INSERT INTO THEME_SONG VALUES(4, 'Lonely Go!', 'Brian the Sun','BORUTO: NEXT GENERATIONS', 2.30, 7.53);
INSERT INTO THEME_SONG VALUES(5, 'BLUE BIRD', 'Ikimono-Gakari','NARUTO-SHIPPUDEN', 3.35, 7.73);


INSERT INTO SHOW_DETAILS VALUES(1, 'NARUTO-ORIGINAL', 'TV-TOKYO', 'Naruto trains for the competition at the academy...');
INSERT INTO SHOW_DETAILS VALUES(2, 'NARUTO-SHIPPUDEN', 'TV-TOKYO', 'Naruto faces his biggest rival for first time...');
INSERT INTO SHOW_DETAILS VALUES(3, 'BOKU NO HERO ACADEMIA', 'YOUPEI', 'The team conquers new war academy...');
INSERT INTO SHOW_DETAILS VALUES(4, 'KIMI NO-NA-WA', 'YOUPEI', '');
INSERT INTO SHOW_DETAILS VALUES(5, 'BORUTO: NEXT GENERATIONS', 'TV-TOKYO', 'The Adventures Continues... ');

INSERT INTO PUBLISHER VALUES(1, 'VIZ-MEDIA', 'TV-TOKYO', 'NARUTO-SHIPPUDEN', 'ENGLISH, JAPANESE', 'WWW.GOGO-ANIME.COM',8.34);
INSERT INTO PUBLISHER VALUES(2, 'VIZ-MEDIA', 'TV-TOKYO', 'KIMI NO-NA-WA', 'ENGLISH, JAPANESE', 'WWW.GOGO-ANIME.COM',9.88);
INSERT INTO PUBLISHER VALUES(3, 'VIZ-MEDIA', 'TV-TOKYO', 'BOKU NO HERO ACADEMIA', 'ENGLISH, JAPANESE', 'WWW.GOGO-ANIME.COM',9.10);
INSERT INTO PUBLISHER VALUES(4, 'VIZ-MEDIA', 'TV-TOKYO', 'NARUTO-ORIGINAL', 'ENGLISH, JAPANESE', 'WWW.GOGO-ANIME.COM',7.21);
INSERT INTO PUBLISHER VALUES(5, 'VIZ-MEDIA', 'TV-TOKYO', 'BORUTO: NEXT GENERATIONS', 'ENGLISH, JAPANESE', 'WWW.GOGO-ANIME.COM', 7.89);

INSERT INTO VIDEOS VALUES(1, 'RAPIDFIRE', 'NARUTO-ORIGINAL', 'WWW.GOGO-ANIME.COM', 7.21);
INSERT INTO VIDEOS VALUES(2, 'RAP', 'KIMI NO-NA-WA', 'WWW.GOGO-ANIME.COM' ,9.88);
INSERT INTO VIDEOS VALUES(3, 'FIRE', 'BOKU NO HERO ACADEMIA', 'WWW.GOGO-ANIME.COM', 9.10);
INSERT INTO VIDEOS VALUES(4, 'RAPIDFIRE', 'BORUTO: NEXT GENERATIONS', 'WWW.GOGO-ANIME.COM', 7.89);
INSERT INTO VIDEOS VALUES(5, 'RARE', 'NARUTO-SHIPPUDEN', 'WWW.GOGO-ANIME.COM', 8.34);

INSERT INTO USERS VALUES(1, 'JERRY','12345','NARUTO-ORIGINAL','WATCHING',8.08);
INSERT INTO USERS VALUES(2,'RICK','12345', 'BORUTO: NEXT GENERATIONS','WATCHING',7.45);
INSERT INTO USERS VALUES(3, 'MORTY','00000','NARUTO-SHIPPUDEN','WILL-WATCH',7.31);
INSERT INTO USERS VALUES(4, 'TOM','TOM123','KIMI NO-NA-WA','WATCHED',10);
INSERT INTO USERS VALUES(5, 'JERRY','QWERTY','BOKU NO HERO ACADEMIA','WATCHING',9.43);

delimiter |
CREATE TRIGGER DEL_USER BEFORE DELETE ON USERS 
  FOR EACH ROW
  BEGIN
      DELETE FROM AUTHOR WHERE COMIC_NAME = USERS.COMIC_NAME;
      END;
| 
delimiter ;
delimiter |
CREATE TRIGGER NEW_COMIC AFTER INSERT ON MANGA_COMIC 
  FOR EACH ROW
  BEGIN
    INSERT INTO SHOW_DETAILS SET COMIC_NAME = NEW.COMIC_NAME ;
	INSERT INTO AUTHOR SET COMIC_NAME = NEW.COMIC_NAME ;
    END;
| 
delimiter ;
delimiter |
CREATE TRIGGER NEW_USER AFTER INSERT ON VIDEOS 
  FOR EACH ROW
  BEGIN
    INSERT INTO USERS SET COMIC_NAME = NEW.COMIC_NAME  ;
    INSERT INTO USERS SET USERNAME = NEW.HOSTNAME  ;
    END;
|
delimiter ;


CREATE VIEW RATING AS SELECT COMIC_ID, COMIC_NAME, AUTHOR, RATING FROM MANGA_COMIC;
CREATE VIEW CHAR_INFO AS SELECT CHARACTER_ID, CHAR_NAME, GENDER, COMIC_NAME, RATING FROM CHARACTERS;
CREATE VIEW COMIC_DETAILS AS SELECT PUBLISHER_ID, PUBLISHER_NAME, CHANNEL_NAME, COMIC_NAME, LINK, RATING FROM PUBLISHER;


CREATE ROLE 'DB_developer', 'DB_read', 'DB_write';

GRANT ALL ON mangacomicdb.* TO 'DB_developer';
GRANT SELECT ON mangacomicdb.* TO 'DB_read';
GRANT INSERT, UPDATE, DELETE ON mangacomicdb.* TO 'DB_write';

CREATE USER 'developer1'@'localhost' IDENTIFIED BY 'developer1pass';
CREATE USER 'read_dev1'@'localhost' IDENTIFIED BY 'read_dev1pass';
CREATE USER 'read_dev2'@'localhost' IDENTIFIED BY 'read_dev2pass';

GRANT 'DB_developer' TO 'developer1'@'localhost';
GRANT 'DB_read' TO 'read_dev1'@'localhost', 'read_dev2'@'localhost';

