SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET character_set_client = utf8mb4 ;

CREATE TABLE IF NOT EXISTS `MANGA-COMIC` (
    `COMIC_ID` INT(2) DEFAULT NULL ,
    `COMIC_NAME` VARCHAR(20) NOT NULL DEFAULT '',
    `COMIC_TYPE` VARCHAR(10) DEFAULT NULL,
    `AUTHOR` VARCHAR(20) DEFAULT NULL,
    `RELEASED` DATE DEFAULT NULL,
    `EPISODES` INT(4) DEFAULT NULL,
    `RATING` INT(2) DEFAULT NULL,
    `STATUS` VARCHAR(10) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;

INSERT INTO `MANGA-COMIC` VALUES
(1, 'NARUTO-ORIGINAL', 'TV SERIES', 'Masashi Kishimoto', '2002-10-04', 220, 9,  'COMPLETED'),
(2, 'NARUTO-SHIPPUDEN', 'TV SERIES', 'Masashi Kishimoto', '2007-02-16', 500, 10, 'COMPLETED'),
(3, 'BORUTO: THE MOVIE OF NARUTO', 'MOVIE', 'UKYO KODACHI', '2015-08-08', 4, 9, 'COMPLETED'),
(4, 'BORUTO: NEXT GENERATIONS', 'TV SERIES', 'UKYO KODACHI', '2017-04-06', 83, 9, 'ON-GOING'),
(5, 'The Day Naruto Became Hokage', 'OVA', 'Masashi Kishimoto', '2016-05-05', 1, 9, 'COMPLETED'),
(6, 'BOKU NO HERO ACADEMIA', 'TV SERIES', 'Kohei Horikoshi', '2016-05-05', 75, 10, 'ON-GOING'),
(7, 'KIMI NO-NA-WA', 'MOVIE', 'MAKATO SHINKAI', '2016-05-04', 1, 10, 'COMPLETED');



CREATE TABLE IF NOT EXISTS `AUTHOR` (
    `AUTHOR_ID` INT(2) NOT NULL DEFAULT '0',
    `AUTHOR_NAME` VARCHAR(20) DEFAULT NULL,
    `DOB` DATE DEFAULT NULL,
    `GENDER` VARCHAR(10) DEFAULT NULL,
    `COMIC_NAME` VARCHAR(20) DEFAULT NULL,
    `RATING` INT(2) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;


INSERT INTO `AUTHOR` VALUES
(1, 'Masashi Kishimoto', '1974-11-08', 'MALE', 'NARUTO-ORIGINAL', 9),
(2, 'Masashi Kishimoto', '1974-11-08', 'MALE', 'NARUTO-SHIPPUDEN', 10),
(3, 'UKYO KODACHI', '1979-04-01', 'MALE', 'BORUTO: NEXT GENERATIONS', 9),
(4, 'MAKATO SHINKAI', '1983-02-19', 'MALE', 'KIMI NO-NA-WA', 10),
(5, 'Kohei Horikoshi', '1987-07-09', 'MALE', 'BOKU NO HERO ACADEMIA', 10);


CREATE TABLE IF NOT EXISTS `CHARACTER` (
    `CHARACTER_ID` INT(2) NOT NULL DEFAULT '0',
    `COMIC_NAME` VARCHAR(20) DEFAULT NULL,
    `CHAR_NAME` VARCHAR(20) DEFAULT NULL,
    `GENDER` VARCHAR(10) DEFAULT NULL,
    `RATING` INT(2) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;

INSERT INTO `CHARACTER` VALUES
(1, 'NARUTO-SHIPPUDEN', 'SAKURA', 'FEMALE', 9),
(2, 'NARUTO-SHIPPUDEN', 'SASUKE', 'MALE', 8),
(3, 'NARUTO-SHIPPUDEN', 'YAMATO', 'MALE', 8),
(4, 'NARUTO-SHIPPUDEN', 'KAKASHI', 'MALE', 9),
(5, 'NARUTO-SHIPPUDEN', 'NARUTO', 'MALE', 9);


CREATE TABLE IF NOT EXISTS `PUBLISHER` (
    `PUBLISHER_ID` INT(2) NOT NULL DEFAULT '0',
    `PUBLISHER_NAME` VARCHAR(20) DEFAULT NULL,
    `CHANNEL` VARCHAR(20) DEFAULT NULL,
    `COMIC_NAME` VARCHAR(20) DEFAULT NULL,
    `LANGUAGES` VARCHAR(20) DEFAULT NULL,
	`PUBLISH_DATE` DATE DEFAULT NULL,
    `RATING` INT(2) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;

INSERT INTO `PUBLISHER` VALUES
(1, 'VIZ-MEDIA', 'TV-Tokyo', 'BORUTO: NEXT GENERATIONS', 'JAPANESE, ENGLISH', '2017-04-06', 9),
(2, 'VIZ-MEDIA', 'TV-Tokyo', 'NARUTO-ORIGINAL', 'JAPANESE, ENGLISH', '2002-10-04', 9),
(3, 'VIZ-MEDIA', 'TV-Tokyo', 'NARUTO-SHIPPUDEN', 'JAPANESE, ENGLISH', '2007-02-16', 10),
(4, 'VIZ-MEDIA', 'TV -okyo', 'BOKU NO HERO ACADEMIA', 'JAPANESE, ENGLISH', '2016-05-05', 10),
(5, 'VIZ-MEDIA', 'TV-Tokyo', 'KIMI NO-NA-WA', 'JAPANESE, ENGLISH', '2016-05-04', 10);


CREATE TABLE IF NOT EXISTS `CURRENT_DETAILS` (
  `COMIC_ID` int(2) NOT NULL DEFAULT '0',
  `COMIC_NAME` varchar(20) DEFAULT NULL,
  `CHANNEL` varchar(20) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;

INSERT INTO `CURRENT_DETAILS` VALUES
(1, 'NARUTO-ORIGINAL', 'Tv Tokyo', '...'),
(2, 'NARUTO-SHIPPUDEN', 'Tv Tokyo', '...'),
(3, 'BOKU NO HERO ACADEMIA', 'YOUPEI', '...'),
(4, 'KIMI NO-NA-WA', 'YOUPEI', '...'),
(5, 'BORUTO: NEXT GENERATIONS', 'TV-Tokyo', 'The Adventures Continues... ');



CREATE TABLE IF NOT EXISTS `THEME-SONG` (
    `SONG_ID` INT(2) NOT NULL DEFAULT '0',
    `NAME` VARCHAR(20) DEFAULT NULL,
    `COMIC_NAME` VARCHAR(20) DEFAULT NULL,
    `ARTIST` VARCHAR(20) DEFAULT NULL,
    `DURATION` INT(2) DEFAULT NULL,
    `RATING` INT(2) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;


INSERT INTO `THEME-SONG` VALUES
(1, 'NOBOY, NO CRY', 'NARUTO-ORIGINAL', 'STANCE PUNKS', 3, 8),
(2, 'BLUE BIRD', 'NARUTO-SHIPPUDEN', 'IKIMONO GAKARI', 3, 8),
(3, 'LONELY GO!', 'BORUTO: NEXT GENERATIONS', 'BRIAN THE SUN', 3, 8),
(4, 'ELENA', 'NARUTO-SHIPPUDEN', 'DIVER', 2, 8),
(5, 'THE TEANGENT', 'KIMI NO-NA-WA', 'GO ON', 3, 10);


CREATE TABLE IF NOT EXISTS `USERS` (
  `USER_ID` INT(2) NOT NULL DEFAULT '0',
  `USERNAME` varchar(20) NOT NULL DEFAULT '',
  `PASSWORD` varchar(20) DEFAULT NULL,
  `COMIC_NAME` varchar(20) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;


INSERT INTO `USERS` VALUES
(1, 'RICK', 'RICK01', 'NARUTO-ORIGINAL',  'ONGOING'),
(2, 'MORTY', '0000', 'BOKU NO HERO ACADEMIA', 'ONGOING'),
(3, 'TOM', 'ABCD','KIMI NO-NA-WA',  'ONGOING'),
(4,  'BEAN', 'QWERTY', 'NARUTO-SHIPPUDEN', 'ONGOING'),
(5,  'JERRY', '12345', 'BORUTO: NEXT GENERATIONS', 'ONGOING');

DELIMITER //
CREATE TRIGGER `D-USER` BEFORE DELETE ON `USERS`
 FOR EACH ROW BEGIN
      DELETE FROM AUTHOR WHERE COMIC_NAME = USERS.COMIC_NAME;
      END
// 
DELIMITER ;

CREATE TABLE IF NOT EXISTS `VIDEOS` (
    `VIDEO_ID` INT(2) NOT NULL DEFAULT '0',
    `HOSTNAME` VARCHAR(20) DEFAULT NULL,
    `COMIC_NAME` VARCHAR(20) DEFAULT NULL,
    `LINK` VARCHAR(20) DEFAULT NULL,
    `RATING` INT(2) DEFAULT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_GENERAL_CI;


INSERT INTO `VIDEOS` VALUES
(1, 'RAPIDFIRE', 'NARUTO-ORIGINAL','WWW.GOGO-ANIME.TV', 7),
(2, 'RARE', 'NARUTO-SHIPPUDEN', 'WWW.GOGO-ANIME.TV', 8),
(3, 'RAPIDFIRE', 'BORUTO: NEXT GENERATIONS', 'WWW.GOGO-ANIME.TV', 7),
(4, 'FIRE', 'BOKU NO HERO ACADEMIA', 'WWW.GOGO-ANIME.TV', 9),
(5, 'RAP', 'KIMI NO-NA-WA', 'WWW.GOGO-ANIME.TV', 10);

DELIMITER //
CREATE TRIGGER `AN-USER` AFTER INSERT ON `VIDEOS`
 FOR EACH ROW BEGIN
    INSERT INTO USERS SET USERNAME = NEW.HOSTNAME  ;
    END
// 
DELIMITER ;

CREATE TABLE IF NOT EXISTS `RATING` (
    `COMIC_ID` INT(2),
    `COMIC_NAME` VARCHAR(25),
    `AUTHOR` VARCHAR(20),
    `RATING` INT(2)
);

DROP TABLE IF EXISTS `RATING`;
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `PULKIT-AGARWAL`@`localhost` 
    SQL SECURITY DEFINER
VIEW `RATING` AS
    SELECT 
        `MANGA-COMIC`.`COMIC_ID` AS `COMIC_ID`,
        `MANGA-COMIC`.`COMIC_NAME` AS `COMIC_NAME`,
        `MANGA-COMIC`.`AUTHOR` AS `AUTHOR`,
        `MANGA-COMIC`.`RATING` AS `RATING`
    FROM
        `MANGA-COMIC`;


CREATE TABLE IF NOT EXISTS `CHAR_INFO` (
    `CHARACTER_ID` INT(2),
    `COMIC_NAME` VARCHAR(25),
    `CHAR_NAME` VARCHAR(20),
    `GENDER` VARCHAR(6),
    `RATING` INT(2)
);

DROP TABLE IF EXISTS `CHAR_INFO`;
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `PULKIT-AGARWAL`@`localhost` 
    SQL SECURITY DEFINER
VIEW `CHAR_INFO` AS
    SELECT 
        `CHARACTER`.`CHARACTER_ID` AS `CHARACTER_ID`,
        `CHARACTER`.`COMIC_NAME` AS `COMIC_NAME`,
        `CHARACTER`.`CHAR_NAME` AS `CHAR_NAME`,
        `CHARACTER`.`GENDER` AS `GENDER`,
        `CHARACTER`.`RATING` AS `RATING`
    FROM
        `CHARACTER`;


CREATE TABLE IF NOT EXISTS `COMIC_DETAILS` (
    `PUBLISHER_ID` INT(2),
    `PUBLISHER_NAME` VARCHAR(25),
    `CHANNEL` VARCHAR(20),
    `COMIC_NAME` VARCHAR(25),
    `RATING` INT(2)
);

DROP TABLE IF EXISTS `COMIC_DETAILS`;
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `PULKIT-AGARWAL`@`localhost` 
    SQL SECURITY DEFINER
VIEW `COMIC_DETAILS` AS
    SELECT 
        `PUBLISHER`.`PUBLISHER_ID` AS `PUBLISHER_ID`,
        `PUBLISHER`.`CHANNEL` AS `CHANNEL`,
        `PUBLISHER`.`PUBLISHER_NAME` AS `PUBLISHER_NAME`,
        `PUBLISHER`.`COMIC_NAME` AS `COMIC_NAME`,
        `PUBLISHER`.`RATING` AS `RATING`
    FROM
        `PUBLISHER`;
        

ALTER TABLE `MANGA-COMIC`
 ADD PRIMARY KEY (`COMIC_NAME`);

ALTER TABLE `CHARACTER`
 ADD PRIMARY KEY (`CHARACTER_ID`), ADD KEY `MANGA_COMIC_FK` (`COMIC_NAME`),
 ADD CONSTRAINT `MANGA_COMIC_FK` FOREIGN KEY (`COMIC_NAME`) REFERENCES `MANGA-COMIC` (`COMIC_NAME`);


ALTER TABLE `AUTHOR`
 ADD PRIMARY KEY (`AUTHOR_ID`), ADD KEY `MANGA_COMIC_FK1` (`COMIC_NAME`),
 ADD CONSTRAINT `MANGA_COMIC_FK1` FOREIGN KEY (`COMIC_NAME`) REFERENCES `MANGA-COMIC` (`COMIC_NAME`);


ALTER TABLE `PUBLISHER`
 ADD PRIMARY KEY (`PUBLISHER_ID`), ADD KEY `MANGA_COMIC_FK2` (`COMIC_NAME`),
 ADD CONSTRAINT `MANGA_COMIC_FK2` FOREIGN KEY (`COMIC_NAME`) REFERENCES `MANGA-COMIC` (`COMIC_NAME`);


ALTER TABLE `CURRENT_DETAILS`
 ADD PRIMARY KEY (`COMIC_ID`), ADD KEY `MANGA_COMIC_FK3` (`COMIC_NAME`),
 ADD CONSTRAINT `MANGA_COMIC_FK3` FOREIGN KEY (`COMIC_NAME`) REFERENCES `MANGA-COMIC` (`COMIC_NAME`);


ALTER TABLE `THEME-SONG`
 ADD PRIMARY KEY (`SONG_ID`), ADD KEY `MANGA_COMIC_FK4` (`COMIC_NAME`),
 ADD CONSTRAINT `MANGA_COMIC_FK4` FOREIGN KEY (`COMIC_NAME`) REFERENCES `MANGA-COMIC` (`COMIC_NAME`);


ALTER TABLE `USERS`
 ADD PRIMARY KEY (`USER_ID`), ADD KEY `MANGA_COMIC_FK5` (`COMIC_NAME`),
 ADD CONSTRAINT `MANGA_COMIC_FK5` FOREIGN KEY (`COMIC_NAME`) REFERENCES `MANGA-COMIC` (`COMIC_NAME`);


ALTER TABLE `VIDEOS`
 ADD PRIMARY KEY (`VIDEO_ID`), ADD KEY `MANGA_COMIC_FK6` (`COMIC_NAME`),
 ADD CONSTRAINT `MANGA_COMIC_FK6` FOREIGN KEY (`COMIC_NAME`) REFERENCES `MANGA-COMIC` (`COMIC_NAME`);

